#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                              \
    external_bar                off:41:0     \
    mouse_follows_focus         on           \
    window_placement            second_child \
    window_topmost              off          \
    window_shadow               on           \
    window_opacity              on           \
    window_border               on           \
    split_ratio                 0.50         \
    split_type                  auto         \
    auto_balance                off          \
    top_padding                 8            \
    left_padding                8            \
    right_padding               8            \
    bottom_padding              8            \
    window_gap                  8            \
    layout                      bsp          \

# space 1: Terminals
# yabai -m rule --add app="Ghostty" space=^1

# space 2: Development
# yabai -m rule --add app="IntelliJ IDEA Ultimate.*" space=^2
# yabai -m rule --add app="IntelliJ IDEA Ultimate.*" title="Preferences" space=^2 manage=off
# yabai -m rule --add app="RustRover.*" space=^2
# yabai -m rule --add app="RustRover.*" title="Preferences" space=^2 manage=off
# yabai -m rule --add app="WebStorm.*" space=^2
# yabai -m rule --add app="WebStorm.*" title="Preferences" space=^2 manage=off
# yabai -m rule --add app="Aqua.*" space=^2
# yabai -m rule --add app="Aqua.*" title="Preferences" space=^2 manage=off
# yabai -m rule --add app="Zed Preview" space=^2

# space 3: Web
# yabai -m rule --add app="Firefox" space=^3
# yabai -m rule --add app="Firefox Nightly" space=^3
# yabai -m rule --add app="Safari" space=^3

# space 4: Discord
# yabai -m rule --add app="Discord Canary.*" space=^4

# space 5: Stack
# yabai -m rule --add app="DataGrip.*" space=^5
# yabai -m rule --add app="DataGrip.*" title="Preferences" space=^5 manage=off
# yabai -m rule --add app="Spotify" space=^5
# yabai -m rule --add app="LINE.*" space=^5

# Disable window management
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="CleanShot X" manage=off
yabai -m rule --add app="DeepL" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Activity Monitor" manage=off

echo "yabai configuration loaded..."
