#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# window rules
yabai -m rule --add app="IntelliJ IDEA Ultimate" manage=off
yabai -m rule --add app="WebStorm" manage=off
yabai -m rule --add app="Aqua" manage=off
yabai -m rule --add app="DataGrip" manage=off

yabai -m rule --add app="Raycast" manage=off mouse_follows_focus=off
yabai -m rule --add app="CleanShot X" manage=off mouse_follows_focus=off
yabai -m rule --add app="DeepL" manage=off mouse_follows_focus=off
yabai -m rule --add app="Calculator" manage=off mouse_follows_focus=off
yabai -m rule --add app="System Settings" manage=off mouse_follows_focus=off

# global settings
yabai -m config                              \
    external_bar                off:41:0     \
    mouse_follows_focus         on           \
    focus_follows_mouse         autoraise    \
    window_placement            second_child \
    window_topmost              off          \
    window_shadow               on           \
    window_opacity              on           \
    window_opacity              on           \
    window_border               on           \
    split_ratio                 0.50         \
    split_type                  auto         \
    auto_balance                off          \
    top_padding                 8            \
    left_padding                8            \
    right_padding               8            \
    bottom_padding              8            \
    window_gap                  8            \
    layout                      bsp          \

echo "yabai configuration loaded.."
