#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                              \
    external_bar                off:41:0     \
    mouse_follows_focus         on           \
    window_placement            second_child \
    window_topmost              off          \
    window_shadow               on           \
    window_opacity              on           \
    window_border               on           \
    split_ratio                 0.50         \
    split_type                  auto         \
    auto_balance                off          \
    top_padding                 8            \
    left_padding                8            \
    right_padding               8            \
    bottom_padding              8            \
    window_gap                  8            \
    layout                      bsp          \

# space 1: terminals
yabai -m rule --add app="Ghostty" space=^1

# space 2: web
yabai -m rule --add app="Firefox" space=^2
yabai -m rule --add app="Firefox Nightly" space=^2
yabai -m rule --add app="Safari" space=^2

# space 3: Development (Zed Preview)
yabai -m rule --add app="Zed Preview" space=^3

# space 4: Development (IDEs)
yabai -m rule --add app="IntelliJ IDEA Ultimate.*" space=^4
yabai -m rule --add app="IntelliJ IDEA Ultimate.*" title="Preferences" space=^4 manage=off
yabai -m rule --add app="RustRover.*" space=^4
yabai -m rule --add app="RustRover.*" title="Preferences" space=^4 manage=off
yabai -m rule --add app="WebStorm.*" space=^4
yabai -m rule --add app="WebStorm.*" title="Preferences" space=^4 manage=off
yabai -m rule --add app="Aqua.*" space=^4
yabai -m rule --add app="Aqua.*" title="Preferences" space=^4 manage=off

# space 5: Discord
yabai -m rule --add app="Discord Canary.*" space=^5

# space 6: Stack
yabai -m rule --add app="DataGrip.*" space=^6
yabai -m rule --add app="DataGrip.*" title="Preferences" space=^6 manage=off
yabai -m rule --add app="Spotify" space=^6
yabai -m rule --add app="LINE.*" space=^6

# Disable window management
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="CleanShot X" manage=off
yabai -m rule --add app="DeepL" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Activity Monitor" manage=off


echo "yabai configuration loaded..."
