# tap
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "minacle/chntpw"
tap "s6n-jp/tap"
tap "sidneys/homebrew"
tap "jdx/tap"

# brew
brew "aria2"
brew "bat"
brew "btop"
brew "chezmoi"
brew "coreutils"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "fastfetch"
brew "gh"
brew "git"
brew "gnupg"
brew "htop"
brew "lazygit"
brew "neovim"
brew "mas"
brew "mise"
brew "onefetch"
brew "ollama"
brew "pinentry-mac"
brew "pkg-config"
brew "rust-analyzer"
brew "ripgrep"
brew "sbt"
brew "starship"
brew "tfenv"
brew "tokei"
brew "topgrade"
brew "jdx/tap/usage"
brew "wget"
brew "wimlib"
brew "minacle/chntpw/chntpw"
brew "s6n-jp/tap/ghr"

# cask
cask "1password"
cask "1password-cli"
cask "alacritty"
cask "adobe-acrobat-reader"
cask "cleanshot"
cask "deepl"
cask "discord-canary"
cask "docker"
cask "figma"
cask "firefox@nightly"
cask "font-0xproto-nerd-font"
cask "font-noto-sans-jp"
cask "google-japanese-ime"
cask "google-chrome@canary"
cask "jetbrains-toolbox"
cask "linear-linear"
cask "notion"
cask "notion-calendar"
cask "obs"
cask "postman"
cask "prismlauncher"
cask "utm@beta"
cask "raycast"
cask "spotify"
cask "thunderbird-daily"
cask "visual-studio-code-insiders"
cask "wireshark"
cask "zed-preview"

# mas
mas "LINE", id: 539883307
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "RunCat", id: 1429033973
mas "Tailscale", id: 1475387142
mas "Xcode", id: 497799835
