tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "heroku/brew"
tap "oven-sh/bun" # "bun" formula tap
brew "asdf"
brew "bat"
brew "btop" # deps formula
brew "bun"
brew "coreutils" # deps formula
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "fd"
brew "gawk" # deps formula
brew "gh"
brew "ghq"
brew "git"
brew "gnupg"
brew "htop"
brew "lazydocker"
brew "lazygit"
brew "neofetch"
brew "mas"
brew "pinentry-mac"
brew "pkg-config"
brew "sbt"
brew "starship"
brew "tfenv" # deps formula
brew "rust-analyzer"
cask "1password"
cask "1password-cli"
cask "alacritty"
cask "cron"
cask "cleanshot"
cask "deepl"
cask "discord"
cask "docker"
cask "figma"
cask "firefox-nightly"
cask "font-noto-sans-jp"
cask "font-jetbrains-mono-nerd-font"
cask "google-japanese-ime"
cask "jetbrains-toolbox"
cask "keycastr"
cask "notion"
cask "obs"
cask "postman"
cask "raycast"
cask "rectangle"
cask "spotify"
cask "slack"
cask "visual-studio-code"
cask "zulu21"
cask "zulu17"
cask "zulu8"
cask "linear-linear"
mas "LINE", id: 539883307
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Outlook", id: 985367838
mas "Hidden Bar", id: 1452453066
mas "NextDNS", id: 1464122853
mas "Toggl Track", id: 1291898086
mas "RunCat", id: 1429033973

cask_args appdir: "~/Applications", require_sha: true
