# tap

tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "heroku/brew"

# brew

brew "1password-cli"
brew "bat"
brew "binutils"
brew "cloudflared"
brew "coreutils"
brew "deno"
brew "fish"
brew "fzf"
brew "ffmpeg"
brew "gawk"
brew "gh"
brew "ghq"
brew "git"
brew "gnupg"
brew "htop"
brew "lazygit"
brew "lazydocker"
brew "nvm"
brew "peco"
brew "pinentry-mac"
brew "pkg-config"
brew "sbt"
brew "starship"
brew "tmux"


# cask

cask_args appdir: "~/Applications", require_sha: true

cask "alacritty"
cask "arc"
cask "cron"
cask "cleanshot"
cask "discord"
cask "deepl"
cask "docker"
cask "figma"
cask "google-japanese-ime"
cask "jetbrains-toolbox"
cask "keybase"
cask "notion"
cask "obsidian"
cask "obs"
cask "stats"
cask "postman"
cask "prismlauncher"
cask "raycast"
cask "spotify"
cask "visual-studio-code"

## Fonts

cask "font-jetbrains-mono-nerd-font"

## JDK
### Appleシリコン(ARM64) に対応したJDKを使用する

cask "zulu17" # JDK17
cask "zulu8" # JDK8

# mas

brew "mas"

mas "BetterSnapTool", id: 417375580
mas "Hidden Bar", id: 1452453066
mas "LINE", id: 539883307
mas "Microsoft Outlook", id: 985367838
mas "Toggl Track: Hours & Time Log", id: 1291898086
