    onboarding = false
[theme]
name = "catppuccin"

[terminal]
default_shell = "/opt/homebrew/bin/fish"

[update]
channel = "stable"
version_check = true
manifest_check = true

[keys]

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "80%"
height = "80%"

[ui]

mouse_scroll_lines = 3

agent_panel_sort = "spaces"
[ui.toast]

[ui.toast.herdr]

[ui.toast.clipboard]

[ui.sound]

[session]

[remote]

[experimental]
pane_history = false

[advanced]
